
project_id = "mksvzhgqnsjfolvskibq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = true

[auth]
enabled = true
site_url = "https://example.com"

[inbucket]
enabled = true
port = 54324

[realtime]
enabled = true

[edge-runtime]
enabled = true

[analytics]
enabled = false
port = 54327
vector_port = 54328

[experimental]
preserve_semantic_native_functions = true

[functions.vimeo-import]
verify_jwt = false

[functions.vimeo-oauth-callback]
verify_jwt = false

[functions.vimeo-oauth-start]
verify_jwt = false

[functions.vimeo-test-connection]
verify_jwt = false

[functions.vimeo-batch-import]
verify_jwt = false

[functions.vimeo-status-check]
verify_jwt = false

[functions.vimeo-env-debug]
verify_jwt = false

[functions.get-vimeo-thumbnail]
verify_jwt = false

[functions.vimeo-get-downloads]
verify_jwt = false
